# Configuración Básica
url: "https://ydmarinb.github.io"
baseurl: ""
title: "ydmarinb Analytics Blog"
description: "Data Engineering, Statistics & Colombian History"

# Colecciones
collections:
  historia:
    output: true
    permalink: /historia/:path/
  statistics:
    output: true
    permalink: /statistics/:path/
  data_engineering:
    output: true
    permalink: /data_engineering/:path/

# Defaults para inyectar variables automáticas
defaults:
  - scope:
      path: ""
      type: historia
    values:
      layout: historia
      lang: "es"
  - scope:
      path: ""
      type: statistics
    values:
      layout: statistics
      lang: "en"
  - scope:
      path: ""
      type: data_engineering
    values:
      layout: data
      lang: "en"

# Plugins a utilizar
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excluir dependencias
exclude:
  - _notebooks
  - .venv
  - build.sh
  - serve.sh
